### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by goodeats** [goodeats/next-image-tagger#1]
- [ ] bug where collectionId is required on Images
- [ ] clean up form validation before sending mutation
- [ ] add tests
- [ ] add husky for pre-commit hooks
- [ ] leverage more re-usable components from shadcn
- [ ] storybook
- [ ] authentication
- [ ] deployment

This project seems at a point where I can create new issues as tickets for this

**Comment by goodeats** [comment]
here we go
